title: Academicons
author: James Walsh
email: jpswalsh@me.com
description: >
  Academicons is licensed under the <a href="http://scripts.sil.org/OFL">SIL OFL 1.1 license</a> •  This page was built using <a href="https://jekyllrb.com/">Jekyll</a> (theme: <a href="https://github.com/jekyll/minima">minima</a>), and uses code from <a href="http://simplegrid.io/">Simple Grid</a> • Request new icons by <a href="https://github.com/jpswalsh/academicons/issues">creating an issue</a> on the GitHub repository
baseurl: "/academicons"
url: "https://jpswalsh.github.io"
github_username:  jpswalsh

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
